apiVersion: v1
kind: Secret
metadata:
    name: codex-secrets
    namespace: codex
    labels:
        app.kubernetes.io/part-of: codex
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:1quHWptdUZGbnLo21fZ+aTgTPL8KolcB3gUaZyDSFLrqbQezX7cTeGX8WpM16SRjyBym,iv:DUDnOpSYr0EqkpHMF5NyNSFnmJAIUmfBQnDzYZgACYg=,tag:AVT9CNSof2UEgAxB08Lyrg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:XfNcMuY=,iv:gaxkK3A7QteCgUz3E/hPLnDXVl/8XBCX0ZYWPr6FHiM=,tag:+5d6Q2LOYWtOuUPtVnUwhQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:mDrRQeztLfVvysN47TqCMu91KmU/ZRqWSdRl3Xc=,iv:UNw887ShpQC5fPea+eFfRKT3McDeMNC9VFQZb/nGKQ8=,tag:J+eBEcDXAjc5m6cLIEV0xQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:DM/0ePbGhpUnC30YY6iCNxJa1keGgNLspTRroaWpWqUtI2M4l/vOk38Ha/MKsZmyhgDXSYCInRjEMMWZMhQB0PllkJA=,iv:zrAGPLjLXZ0vCQ2sH1cgrH18ZCn7sMiG9E/JpZokf0o=,tag:WLp3SSk3NgnGrQhogg3xMQ==,type:str]
    OPENGRAPH_IO_API_KEY: ""
    GOOGLE_CLIENT_ID: ""
    GOOGLE_CLIENT_SECRET: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15eetmfpjrl5lttgfn0f7qwsy39gzasds35f68rpc76ujfvz8ts6qt9w2mw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLenVFd1pOOWxiZ21aM2hD
            Z3YyN1BVZFpvWERZZms0NjBkTkMwckY5WFZRClRsZHhzaUhOZ0lEajZKYWNMNk5w
            RFQxK2lZS01LMlozTDg2OXlXK1U5UW8KLS0tIFRXenJPN1BXMndiTWFGRnp2dGp6
            TG9oREdYSDVLSVN0TDZ4empkS2tndkkKNgHlY9ukN9U72fdi1M3DywO4b8d34WlX
            DUa711vHcfYrCwV5oOZU6DEGU3srMScutUq1TLY8lVy+8n00ues9aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T01:42:59Z"
    mac: ENC[AES256_GCM,data:uQ3X79uxBSb1VQ3522OQFxMCMiKXP2mly6NM4kYX59Yp88UMZX+s3dX6PgL3A296LEsgzDIlmXHhCgfsPkg/uGaAC629aIObHci2MFPSr2IdU5O7gpy+lWnZfoS4PSBkoSdz/ntkxfbx+OZTIhyKySE4HB1aK9kZZFQO0NZhUzM=,iv:W1xMREvnZ9/W/x5mom55fR5asuNKv2Oe0JSMYmK1Bvo=,tag:ETGUjhXmC8xq4XooVxnyyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
