apiVersion: v1
kind: Secret
metadata:
    name: codex-secrets
    namespace: codex
    labels:
        app.kubernetes.io/part-of: codex
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:zoATasmDg3LSkEbqQMFtRNrRQb6WTZOUyZtXjz4PuK4Oz6gFLV7g5r64UM4DZBTvCOhT,iv:8MiYBvE68tyks5hrHvyf5Dc/NHiCuXjK5Dw/4joi/Is=,tag:rn4GKGHphhUWij7m2+ceLg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:R8se+p0=,iv:IvTWEUSivZ+If80SQd4Di7GbG+yKb7Wp4Ft99XnXiaY=,tag:uLVU/mgG5G3FYHq0SbZgZQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hHUsQaj/PllnbxUUjSbyqz6KDxR6BiVmsns=,iv:53FlkGZg9np+cFnXF3xm/1D6y6t3av7Ot1jzXHMK1fc=,tag:+w/oRwb4yzj8Wx3yXQtl4A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:oaSF/bvUj5JbgmxP5HnXA797IXv2iztLCtdfWk8KLqmznDOrJ//qowIBP3QR/osPI0yfIrqxzDQe7pVllHqK8Fs=,iv:JdOGIuNhH66gtaXcdGy5NfHQQ1fBwHVLtVxd/sAQVPc=,tag:QucMEqEWwfjw1JpmkmpqUA==,type:str]
    OPENGRAPH_IO_API_KEY: ""
    GOOGLE_CLIENT_ID: ""
    GOOGLE_CLIENT_SECRET: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15eetmfpjrl5lttgfn0f7qwsy39gzasds35f68rpc76ujfvz8ts6qt9w2mw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NzEzTGk0b3ViNCsxNFhw
            eU1RNkUvcHZ4cEhVOU1BM2VtZ2lOcXMrMlFVCmE3emlUZ0oxUWNBOHJYY2REaFhX
            TUo0dWxQanBOYlNsV0ZLRjBOaGp0YjQKLS0tIEpvQVMxcjhyVjE5Qk04eGhVUi85
            SDJlRmJqd1BMR2NCSllZblI2cmJpQU0KOcjhTKvt1ZLkWwLh8MGqNvfT+EPx3hcX
            JBQPSF5fRLHbrMMhpJNYeM+v9RDqOt2fHNvBavOqpLY/ufAn/pc1gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T01:42:59Z"
    mac: ENC[AES256_GCM,data:wgjZfTHiP82JVF8KjwkNJ3nJJpm7L1KKo5Tpr0RZHQYMVX4KjQ7VQPGIrgw7YRhJHHAvzkbWcds7ypySueB0r5LWqyRglixHe2/a+c2q1wgb4ItE9o847f7HEUTQ+S5OOaKHKlv75YmKhKWWnEh0hO8f0vpY+qxrxnh1iDcicSw=,iv:2tXVpeHRoTZpGwjT6OwT0LE0mQrLq/QIVihQNv7Yoe4=,tag:nBxT6hPhbud8LSiN+aAx1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
