apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codex

resources:
  - namespace.yml
  - configmap.yml
  - secrets.yml
  - pvc.yml
  - postgres-deployment.yml
  - backend-deployment.yml
  - frontend-deployment.yml
  - ingress.yml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
